// P1: the AppHost is the composition root, and it exists for DEVELOPMENT. One command brings the
// system up:   dotnet run --project src/WorkInPoland.AppHost
//
// It is NOT the production topology. Production is described by flyio/*.fly.toml and the deploy
// workflow; there is deliberately no publish-mode branch here (P1: "a manifest generator, not a
// second runtime").
//
// No secret is a literal in this file (P5). The one mandatory secret — the development signing key —
// is generated by scripts/setup.sh into `dotnet user-secrets` and enters as an Aspire parameter.
// Optional integrations are read as `Configuration["Parameters:x"] ?? ""` so a missing value degrades
// a feature instead of failing startup (P8).

var builder = DistributedApplication.CreateBuilder(args);

// ── Parameters ───────────────────────────────────────────────────────────────────────────────
// The one mandatory secret: authservice's only signing key (PKCS#8 PEM). Local only — never a
// production trust root.
var jwtPrivateKey = builder.AddParameter("jwt-private-key", secret: true);

string Optional(string name) => builder.Configuration[$"Parameters:{name}"] ?? "";

// ── State: one Postgres, one database per service (P3) ───────────────────────────────────────
var postgres = builder.AddPostgres("postgres")
    .WithDataVolume("work-in-poland-pgdata");
var apidb = postgres.AddDatabase("apidb");
var authdb = postgres.AddDatabase("authdb");

// ── Identity: authservice, run from its PUBLISHED image; its source is never modified (ADR 0003) ──
// A fixed host port, not a floating one: it is the issuer origin the API and the web middleware
// validate against, and the origin its emails and OAuth redirects name.
const int AuthServicePort = 5080;
const string FrontendOrigin = "http://localhost:3000";
const string AuthServiceOrigin = "http://localhost:5080";

var authservice = builder.AddContainer("authservice", "ghcr.io/konradcinkusz/authservice", "v0.3.4")
    .WithHttpEndpoint(port: AuthServicePort, targetPort: 8080, name: "http", isProxied: false)
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", "Production")
    .WithEnvironment("DATABASE_PROVIDER", "PostgreSQL")
    .WithEnvironment("Database__SchemaMode", "Migrate")
    .WithEnvironment("Database__MigrationsAssembly", "AuthService.Migrations.PostgreSQL")
    .WithEnvironment("ConnectionStrings__DefaultConnection", authdb.Resource.ConnectionStringExpression)
    .WithEnvironment("Jwt__Algorithm", "RS256")
    .WithEnvironment("Jwt__PrivateKeyPem", jwtPrivateKey)
    .WithEnvironment("Jwt__Issuer", "WorkInPoland")
    .WithEnvironment("Jwt__Audience", "WorkInPoland")
    .WithEnvironment("App__Name", "Work in Poland")
    .WithEnvironment("FrontendBaseUrl", FrontendOrigin)
    .WithEnvironment("OAuth__PostLoginRedirectBaseUrl", FrontendOrigin)
    .WithEnvironment("OAuth__CallbackBaseUrl", AuthServiceOrigin)
    .WithEnvironment("ConsentVersions__Terms", "2026-10-05")
    .WithEnvironment("ConsentVersions__Privacy", "2026-10-05")
    .WithEnvironment("ConsentVersions__Cookies", "2026-10-05")
    .WithHttpHealthCheck("/health/ready")
    .WaitFor(authdb);

// Optional integrations (P8): present -> the feature is on; absent -> authservice degrades to its
// no-op (emails are logged, social buttons are not rendered).
void WhenSet(string parameter, string environmentVariable)
{
    var value = Optional(parameter);
    if (!string.IsNullOrWhiteSpace(value))
    {
        authservice.WithEnvironment(environmentVariable, value);
    }
}

WhenSet("sendgrid-api-key", "SendGrid__ApiKey");
WhenSet("sendgrid-from-email", "SendGrid__FromEmail");
WhenSet("google-client-id", "OAuth__Google__ClientId");
WhenSet("google-client-secret", "OAuth__Google__ClientSecret");
WhenSet("github-client-id", "OAuth__GitHub__ClientId");
WhenSet("github-client-secret", "OAuth__GitHub__ClientSecret");

// ── The API: the one service. Owns apidb; validates tokens, mints none (P5) ──────────────────
var api = builder.AddProject<Projects.WorkInPoland_Api>("api")
    .WithReference(apidb)
    .WaitFor(apidb)
    .WaitFor(authservice)
    .WithEnvironment("Jwt__Authority", AuthServiceOrigin)
    .WithEnvironment("Jwt__Issuer", "WorkInPoland")
    .WithEnvironment("Jwt__Audience", "WorkInPoland")
    // authservice is plain http on localhost here; production never sets this.
    .WithEnvironment("Jwt__RequireHttpsMetadata", "false")
    .WithEnvironment("Seed__Demo", "true")
    .WithHttpHealthCheck("/health");

// ── The product surface: Next.js, one pnpm workspace member ──────────────────────────────────
// The BFF resolves the API through its candidate ladder (explicit env -> the service-discovery
// variables Aspire injects via WithReference -> internal DNS -> localhost), so there is no
// per-environment code here.
builder.AddJavaScriptApp("web", "../../web/app", "dev")
    .WithPnpm()
    .WithHttpEndpoint(port: 3000, env: "PORT", isProxied: false)
    .WithReference(api)
    .WaitFor(api)
    .WithEnvironment("AUTH_BASE_URL", AuthServiceOrigin)
    .WithEnvironment("AUTH_PUBLIC_URL", AuthServiceOrigin)
    .WithEnvironment("AUTH_ISSUER", "WorkInPoland")
    .WithEnvironment("AUTH_AUDIENCE", "WorkInPoland")
    .WithEnvironment("PUBLIC_SITE_URL", FrontendOrigin)
    .WithEnvironment("CONSENT_TERMS_VERSION", "2026-10-05")
    .WithEnvironment("CONSENT_PRIVACY_VERSION", "2026-10-05");

builder.Build().Run();
