#requires -Version 7
<#
.SYNOPSIS
  One-command onboarding on Windows (REPO-BASELINE §3). Twin of scripts/setup.sh.

.DESCRIPTION
  .\scripts\setup.ps1          check prerequisites, install deps and hooks, generate the dev key
  .\scripts\setup.ps1 -Check   strict: report what is missing BY NAME and exit non-zero; changes nothing

  No openssl is needed: the development signing key is generated by Node (already a prerequisite).
#>
param([switch]$Check)
$ErrorActionPreference = 'Stop'
Set-Location (git rev-parse --show-toplevel)

$missing = @()
function Test-Tool([string]$name) { [bool](Get-Command $name -ErrorAction SilentlyContinue) }
function Add-Missing([string]$what, [string]$how) {
  $script:missing += $what
  Write-Host "  x $what" -ForegroundColor Red
  Write-Host "    $how"
}

Write-Host "`n1. Prerequisites" -ForegroundColor White
if (Test-Tool dotnet) {
  $v = [version](dotnet --version).Split('-')[0]
  if ($v.Major -ge 10) { Write-Host "  ok .NET SDK $v" -ForegroundColor Green }
  else { Add-Missing ".NET SDK 10 (found $v)" 'https://dotnet.microsoft.com/download/dotnet/10.0' }
} else { Add-Missing '.NET SDK 10' 'https://dotnet.microsoft.com/download/dotnet/10.0' }

if (Test-Tool node) {
  $n = [version](node -p 'process.versions.node')
  if ($n.Major -ge 22) { Write-Host "  ok node $n" -ForegroundColor Green }
  else { Add-Missing "node 22 or newer (found $n)" 'https://nodejs.org/en/download' }
} else { Add-Missing 'node 22 or newer' 'https://nodejs.org/en/download' }

if (Test-Tool pnpm) { Write-Host "  ok pnpm $(pnpm -v)" -ForegroundColor Green }
else { Add-Missing 'pnpm' 'corepack enable; corepack prepare pnpm@latest --activate  (or https://pnpm.io/installation)' }

$dockerOk = (Test-Tool docker) -and ((docker info 2>$null) -ne $null) -and ($LASTEXITCODE -eq 0)
if ($dockerOk) { Write-Host '  ok container engine' -ForegroundColor Green }
else { Add-Missing 'a running container engine (Docker Desktop or Podman)' 'https://docs.docker.com/get-docker/ - the AppHost needs it for Postgres and authservice' }

if (Test-Tool gitleaks) { Write-Host '  ok gitleaks' -ForegroundColor Green }
elseif ($dockerOk) { Write-Host '  ok no gitleaks, but Docker is running - the hook uses the container CI uses' -ForegroundColor Green }
else { Add-Missing 'a secret scanner (gitleaks, or Docker)' 'The pre-commit hook refuses to commit without one (P5). https://github.com/gitleaks/gitleaks#installing' }

if ($Check) {
  if ($missing.Count -eq 0) { Write-Host "`nAll prerequisites present." -ForegroundColor Green; exit 0 }
  Write-Host "`nMissing: $($missing -join ', ')" -ForegroundColor Red; exit 1
}
if ($missing.Count -gt 0) { Write-Host "`nFix the missing prerequisites above, then re-run." -ForegroundColor Red; exit 1 }

Write-Host "`n2. Dependencies" -ForegroundColor White
dotnet restore WorkInPoland.sln | Out-Null
$env:PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = '1'
pnpm install --frozen-lockfile | Out-Null
Write-Host '  ok restored' -ForegroundColor Green

Write-Host "`n3. Git hooks" -ForegroundColor White
$hook = Join-Path (git rev-parse --git-path hooks) 'pre-commit'
New-Item -ItemType Directory -Force -Path (Split-Path $hook) | Out-Null
Copy-Item scripts/hooks/pre-commit $hook -Force
Write-Host "  ok pre-commit secret scan installed ($hook)" -ForegroundColor Green

Write-Host "`n4. Local secret store (dotnet user-secrets, behind Aspire parameters)" -ForegroundColor White
$apphost = 'src/WorkInPoland.AppHost'
dotnet user-secrets init --project $apphost 2>$null | Out-Null

Write-Host "`n5. Development signing key (the one mandatory secret - generated, never invented)" -ForegroundColor White
$existing = dotnet user-secrets list --project $apphost 2>$null | Select-String '^Parameters:jwt-private-key'
if ($existing) { Write-Host '  ok already set (Parameters:jwt-private-key)' -ForegroundColor Green }
else {
  $key = (node scripts/generate-dev-key.mjs) -join "`n"
  dotnet user-secrets set 'Parameters:jwt-private-key' $key --project $apphost | Out-Null
  Write-Host '  ok generated an RSA-2048 PKCS#8 key into the user-secrets store' -ForegroundColor Green
}

Write-Host "`n6. Optional integrations (skipped by default)" -ForegroundColor White
Write-Host '  (optional - real email delivery) dotnet user-secrets set "Parameters:sendgrid-api-key" "<key>" --project src/WorkInPoland.AppHost'
Write-Host '  (optional - Google/GitHub sign-in) Parameters:google-client-id / google-client-secret / github-client-id / github-client-secret'

Write-Host "`nDone. Next:  dotnet run --project src/WorkInPoland.AppHost" -ForegroundColor Green
